//go:build darwin && arm64 && cgo

// GENERATED by scripts/gen_mlxc_shim.py — do not edit.
#include "mlx_shim.h"
#include "mlx_shim_dispatch_gen.h"

int mlx_abs(mlx_array* res, const mlx_array a, const mlx_stream s) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_abs(res, a, s);
}
int mlx_add(mlx_array* res, const mlx_array a, const mlx_array b, const mlx_stream s) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_add(res, a, b, s);
}
int mlx_arange(mlx_array* res, double start, double stop, double step, mlx_dtype dtype, const mlx_stream s) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_arange(res, start, stop, step, dtype, s);
}
int mlx_argmax(mlx_array* res, const mlx_array a, bool keepdims, const mlx_stream s) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_argmax(res, a, keepdims, s);
}
int mlx_argmax_axis(mlx_array* res, const mlx_array a, int axis, bool keepdims, const mlx_stream s) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_argmax_axis(res, a, axis, keepdims, s);
}
int mlx_argpartition_axis(mlx_array* res, const mlx_array a, int kth, int axis, const mlx_stream s) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_argpartition_axis(res, a, kth, axis, s);
}
const float* mlx_array_data_float32(const mlx_array arr) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return NULL; }
  return mlx_dispatch.mlx_array_data_float32(arr);
}
const int64_t* mlx_array_data_int64(const mlx_array arr) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return NULL; }
  return mlx_dispatch.mlx_array_data_int64(arr);
}
const uint32_t* mlx_array_data_uint32(const mlx_array arr) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return NULL; }
  return mlx_dispatch.mlx_array_data_uint32(arr);
}
const uint8_t* mlx_array_data_uint8(const mlx_array arr) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return NULL; }
  return mlx_dispatch.mlx_array_data_uint8(arr);
}
mlx_dtype mlx_array_dtype(const mlx_array arr) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 0; }
  return mlx_dispatch.mlx_array_dtype(arr);
}
int mlx_array_eval(mlx_array arr) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_array_eval(arr);
}
int mlx_array_free(mlx_array arr) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_array_free(arr);
}
size_t mlx_array_ndim(const mlx_array arr) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 0; }
  return mlx_dispatch.mlx_array_ndim(arr);
}
mlx_array mlx_array_new(void) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return (mlx_array){0}; }
  return mlx_dispatch.mlx_array_new();
}
mlx_array mlx_array_new_data(const void* data, const int* shape, int dim, mlx_dtype dtype) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return (mlx_array){0}; }
  return mlx_dispatch.mlx_array_new_data(data, shape, dim, dtype);
}
mlx_array mlx_array_new_int(int val) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return (mlx_array){0}; }
  return mlx_dispatch.mlx_array_new_int(val);
}
int mlx_array_set(mlx_array* arr, const mlx_array src) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_array_set(arr, src);
}
const int* mlx_array_shape(const mlx_array arr) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return NULL; }
  return mlx_dispatch.mlx_array_shape(arr);
}
size_t mlx_array_size(const mlx_array arr) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 0; }
  return mlx_dispatch.mlx_array_size(arr);
}
int mlx_astype(mlx_array* res, const mlx_array a, mlx_dtype dtype, const mlx_stream s) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_astype(res, a, dtype, s);
}
int mlx_async_eval(const mlx_vector_array outputs) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_async_eval(outputs);
}
int mlx_clear_cache(void) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_clear_cache();
}
int mlx_closure_apply(mlx_vector_array* res, mlx_closure cls, const mlx_vector_array input) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_closure_apply(res, cls, input);
}
int mlx_closure_free(mlx_closure cls) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_closure_free(cls);
}
mlx_closure mlx_closure_new_func_payload(int (*fun)(mlx_vector_array*, const mlx_vector_array, void*), void* payload, void (*dtor)(void*)) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return (mlx_closure){0}; }
  return mlx_dispatch.mlx_closure_new_func_payload(fun, payload, dtor);
}
int mlx_compile(mlx_closure* res, const mlx_closure fun, bool shapeless) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_compile(res, fun, shapeless);
}
int mlx_concatenate_axis(mlx_array* res, const mlx_vector_array arrays, int axis, const mlx_stream s) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_concatenate_axis(res, arrays, axis, s);
}
int mlx_conv1d(mlx_array* res, const mlx_array input, const mlx_array weight, int stride, int padding, int dilation, int groups, const mlx_stream s) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_conv1d(res, input, weight, stride, padding, dilation, groups, s);
}
int mlx_cos(mlx_array* res, const mlx_array a, const mlx_stream s) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_cos(res, a, s);
}
mlx_stream mlx_default_gpu_stream_new(void) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return (mlx_stream){0}; }
  return mlx_dispatch.mlx_default_gpu_stream_new();
}
int mlx_dequantize(mlx_array* res, const mlx_array w, const mlx_array scales, const mlx_array biases , mlx_optional_int group_size, mlx_optional_int bits, const char* mode, const mlx_array global_scale , mlx_optional_dtype dtype, const mlx_stream s) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_dequantize(res, w, scales, biases, group_size, bits, mode, global_scale, dtype, s);
}
int mlx_device_free(mlx_device dev) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_device_free(dev);
}
int mlx_device_is_available(bool* avail, mlx_device dev) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_device_is_available(avail, dev);
}
mlx_device mlx_device_new_type(mlx_device_type type, int index) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return (mlx_device){0}; }
  return mlx_dispatch.mlx_device_new_type(type, index);
}
int mlx_divide(mlx_array* res, const mlx_array a, const mlx_array b, const mlx_stream s) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_divide(res, a, b, s);
}
int mlx_enable_compile(void) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_enable_compile();
}
int mlx_equal(mlx_array* res, const mlx_array a, const mlx_array b, const mlx_stream s) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_equal(res, a, b, s);
}
int mlx_exp(mlx_array* res, const mlx_array a, const mlx_stream s) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_exp(res, a, s);
}
int mlx_fast_metal_kernel_apply(mlx_vector_array* outputs, mlx_fast_metal_kernel cls, const mlx_vector_array inputs, const mlx_fast_metal_kernel_config config, const mlx_stream stream) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_fast_metal_kernel_apply(outputs, cls, inputs, config, stream);
}
int mlx_fast_metal_kernel_config_add_output_arg(mlx_fast_metal_kernel_config cls, const int* shape, size_t size, mlx_dtype dtype) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_fast_metal_kernel_config_add_output_arg(cls, shape, size, dtype);
}
int mlx_fast_metal_kernel_config_add_template_arg_bool(mlx_fast_metal_kernel_config cls, const char* name, bool value) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_fast_metal_kernel_config_add_template_arg_bool(cls, name, value);
}
int mlx_fast_metal_kernel_config_add_template_arg_dtype(mlx_fast_metal_kernel_config cls, const char* name, mlx_dtype dtype) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_fast_metal_kernel_config_add_template_arg_dtype(cls, name, dtype);
}
int mlx_fast_metal_kernel_config_add_template_arg_int(mlx_fast_metal_kernel_config cls, const char* name, int value) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_fast_metal_kernel_config_add_template_arg_int(cls, name, value);
}
void mlx_fast_metal_kernel_config_free(mlx_fast_metal_kernel_config cls) {
  if (mlx_shim_ready()) mlx_dispatch.mlx_fast_metal_kernel_config_free(cls);
}
mlx_fast_metal_kernel_config mlx_fast_metal_kernel_config_new(void) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return (mlx_fast_metal_kernel_config){0}; }
  return mlx_dispatch.mlx_fast_metal_kernel_config_new();
}
int mlx_fast_metal_kernel_config_set_grid(mlx_fast_metal_kernel_config cls, int grid1, int grid2, int grid3) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_fast_metal_kernel_config_set_grid(cls, grid1, grid2, grid3);
}
int mlx_fast_metal_kernel_config_set_init_value(mlx_fast_metal_kernel_config cls, float value) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_fast_metal_kernel_config_set_init_value(cls, value);
}
int mlx_fast_metal_kernel_config_set_thread_group(mlx_fast_metal_kernel_config cls, int thread1, int thread2, int thread3) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_fast_metal_kernel_config_set_thread_group(cls, thread1, thread2, thread3);
}
void mlx_fast_metal_kernel_free(mlx_fast_metal_kernel cls) {
  if (mlx_shim_ready()) mlx_dispatch.mlx_fast_metal_kernel_free(cls);
}
mlx_fast_metal_kernel mlx_fast_metal_kernel_new(const char* name, const mlx_vector_string input_names, const mlx_vector_string output_names, const char* source, const char* header, bool ensure_row_contiguous, bool atomic_outputs) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return (mlx_fast_metal_kernel){0}; }
  return mlx_dispatch.mlx_fast_metal_kernel_new(name, input_names, output_names, source, header, ensure_row_contiguous, atomic_outputs);
}
int mlx_fast_rms_norm(mlx_array* res, const mlx_array x, const mlx_array weight , float eps, const mlx_stream s) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_fast_rms_norm(res, x, weight, eps, s);
}
int mlx_fast_rope(mlx_array* res, const mlx_array x, int dims, bool traditional, mlx_optional_float base, float scale, int offset, const mlx_array freqs , const mlx_stream s) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_fast_rope(res, x, dims, traditional, base, scale, offset, freqs, s);
}
int mlx_fast_rope_dynamic(mlx_array* res, const mlx_array x, int dims, bool traditional, mlx_optional_float base, float scale, const mlx_array offset, const mlx_array freqs , const mlx_stream s) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_fast_rope_dynamic(res, x, dims, traditional, base, scale, offset, freqs, s);
}
int mlx_fast_scaled_dot_product_attention(mlx_array* res, const mlx_array queries, const mlx_array keys, const mlx_array values, float scale, const char* mask_mode, const mlx_array mask_arr , const mlx_array sinks , const mlx_stream s) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_fast_scaled_dot_product_attention(res, queries, keys, values, scale, mask_mode, mask_arr, sinks, s);
}
int mlx_gather(mlx_array* res, const mlx_array a, const mlx_vector_array indices, const int* axes, size_t axes_num, const int* slice_sizes, size_t slice_sizes_num, const mlx_stream s) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_gather(res, a, indices, axes, axes_num, slice_sizes, slice_sizes_num, s);
}
int mlx_gather_qmm(mlx_array* res, const mlx_array x, const mlx_array w, const mlx_array scales, const mlx_array biases , const mlx_array lhs_indices , const mlx_array rhs_indices , bool transpose, mlx_optional_int group_size, mlx_optional_int bits, const char* mode, bool sorted_indices, const mlx_stream s) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_gather_qmm(res, x, w, scales, biases, lhs_indices, rhs_indices, transpose, group_size, bits, mode, sorted_indices, s);
}
int mlx_gather_single(mlx_array* res, const mlx_array a, const mlx_array indices, int axis, const int* slice_sizes, size_t slice_sizes_num, const mlx_stream s) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_gather_single(res, a, indices, axis, slice_sizes, slice_sizes_num, s);
}
int mlx_get_active_memory(size_t* res) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_get_active_memory(res);
}
int mlx_get_cache_memory(size_t* res) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_get_cache_memory(res);
}
int mlx_get_default_device(mlx_device* dev) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_get_default_device(dev);
}
int mlx_get_default_stream(mlx_stream* stream, mlx_device dev) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_get_default_stream(stream, dev);
}
int mlx_get_memory_limit(size_t* res) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_get_memory_limit(res);
}
int mlx_get_peak_memory(size_t* res) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_get_peak_memory(res);
}
int mlx_less_equal(mlx_array* res, const mlx_array a, const mlx_array b, const mlx_stream s) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_less_equal(res, a, b, s);
}
int mlx_log(mlx_array* res, const mlx_array a, const mlx_stream s) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_log(res, a, s);
}
int mlx_log1p(mlx_array* res, const mlx_array a, const mlx_stream s) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_log1p(res, a, s);
}
int mlx_matmul(mlx_array* res, const mlx_array a, const mlx_array b, const mlx_stream s) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_matmul(res, a, b, s);
}
int mlx_max_axes(mlx_array* res, const mlx_array a, const int* axes, size_t axes_num, bool keepdims, const mlx_stream s) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_max_axes(res, a, axes, axes_num, keepdims, s);
}
int mlx_maximum(mlx_array* res, const mlx_array a, const mlx_array b, const mlx_stream s) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_maximum(res, a, b, s);
}
int mlx_mean_axes(mlx_array* res, const mlx_array a, const int* axes, size_t axes_num, bool keepdims, const mlx_stream s) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_mean_axes(res, a, axes, axes_num, keepdims, s);
}
int mlx_metal_start_capture(const char* path) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_metal_start_capture(path);
}
int mlx_metal_stop_capture(void) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_metal_stop_capture();
}
int mlx_multiply(mlx_array* res, const mlx_array a, const mlx_array b, const mlx_stream s) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_multiply(res, a, b, s);
}
int mlx_negative(mlx_array* res, const mlx_array a, const mlx_stream s) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_negative(res, a, s);
}
int mlx_pad(mlx_array* res, const mlx_array a, const int* axes, size_t axes_num, const int* low_pad_size, size_t low_pad_size_num, const int* high_pad_size, size_t high_pad_size_num, const mlx_array pad_value, const char* mode, const mlx_stream s) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_pad(res, a, axes, axes_num, low_pad_size, low_pad_size_num, high_pad_size, high_pad_size_num, pad_value, mode, s);
}
int mlx_power(mlx_array* res, const mlx_array a, const mlx_array b, const mlx_stream s) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_power(res, a, b, s);
}
int mlx_quantize(mlx_vector_array* res, const mlx_array w, mlx_optional_int group_size, mlx_optional_int bits, const char* mode, const mlx_array global_scale , const mlx_stream s) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_quantize(res, w, group_size, bits, mode, global_scale, s);
}
int mlx_quantized_matmul(mlx_array* res, const mlx_array x, const mlx_array w, const mlx_array scales, const mlx_array biases , bool transpose, mlx_optional_int group_size, mlx_optional_int bits, const char* mode, const mlx_stream s) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_quantized_matmul(res, x, w, scales, biases, transpose, group_size, bits, mode, s);
}
int mlx_repeat_axis(mlx_array* res, const mlx_array arr, int repeats, int axis, const mlx_stream s) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_repeat_axis(res, arr, repeats, axis, s);
}
int mlx_reset_peak_memory(void) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_reset_peak_memory();
}
int mlx_reshape(mlx_array* res, const mlx_array a, const int* shape, size_t shape_num, const mlx_stream s) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_reshape(res, a, shape, shape_num, s);
}
int mlx_rsqrt(mlx_array* res, const mlx_array a, const mlx_stream s) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_rsqrt(res, a, s);
}
int mlx_set_cache_limit(size_t* res, size_t limit) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_set_cache_limit(res, limit);
}
int mlx_set_compile_mode(mlx_compile_mode mode) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_set_compile_mode(mode);
}
void mlx_set_error_handler(mlx_error_handler_func handler, void* data, void (*dtor)(void*)) {
  if (mlx_shim_ready()) mlx_dispatch.mlx_set_error_handler(handler, data, dtor);
}
int mlx_set_memory_limit(size_t* res, size_t limit) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_set_memory_limit(res, limit);
}
int mlx_sigmoid(mlx_array* res, const mlx_array a, const mlx_stream s) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_sigmoid(res, a, s);
}
int mlx_sin(mlx_array* res, const mlx_array a, const mlx_stream s) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_sin(res, a, s);
}
int mlx_slice(mlx_array* res, const mlx_array a, const int* start, size_t start_num, const int* stop, size_t stop_num, const int* strides, size_t strides_num, const mlx_stream s) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_slice(res, a, start, start_num, stop, stop_num, strides, strides_num, s);
}
int mlx_slice_update(mlx_array* res, const mlx_array src, const mlx_array update, const int* start, size_t start_num, const int* stop, size_t stop_num, const int* strides, size_t strides_num, const mlx_stream s) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_slice_update(res, src, update, start, start_num, stop, stop_num, strides, strides_num, s);
}
int mlx_softmax(mlx_array* res, const mlx_array a, bool precise, const mlx_stream s) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_softmax(res, a, precise, s);
}
int mlx_softmax_axis(mlx_array* res, const mlx_array a, int axis, bool precise, const mlx_stream s) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_softmax_axis(res, a, axis, precise, s);
}
int mlx_split(mlx_vector_array* res, const mlx_array a, int num_splits, int axis, const mlx_stream s) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_split(res, a, num_splits, axis, s);
}
int mlx_split_sections(mlx_vector_array* res, const mlx_array a, const int* indices, size_t indices_num, int axis, const mlx_stream s) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_split_sections(res, a, indices, indices_num, axis, s);
}
int mlx_sqrt(mlx_array* res, const mlx_array a, const mlx_stream s) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_sqrt(res, a, s);
}
int mlx_square(mlx_array* res, const mlx_array a, const mlx_stream s) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_square(res, a, s);
}
int mlx_squeeze_axis(mlx_array* res, const mlx_array a, int axis, const mlx_stream s) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_squeeze_axis(res, a, axis, s);
}
int mlx_stack(mlx_array* res, const mlx_vector_array arrays, const mlx_stream s) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_stack(res, arrays, s);
}
int mlx_stream_free(mlx_stream stream) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_stream_free(stream);
}
mlx_stream mlx_stream_new_device(mlx_device dev) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return (mlx_stream){0}; }
  return mlx_dispatch.mlx_stream_new_device(dev);
}
int mlx_subtract(mlx_array* res, const mlx_array a, const mlx_array b, const mlx_stream s) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_subtract(res, a, b, s);
}
int mlx_sum_axes(mlx_array* res, const mlx_array a, const int* axes, size_t axes_num, bool keepdims, const mlx_stream s) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_sum_axes(res, a, axes, axes_num, keepdims, s);
}
int mlx_synchronize(mlx_stream stream) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_synchronize(stream);
}
int mlx_take_along_axis(mlx_array* res, const mlx_array a, const mlx_array indices, int axis, const mlx_stream s) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_take_along_axis(res, a, indices, axis, s);
}
int mlx_tanh(mlx_array* res, const mlx_array a, const mlx_stream s) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_tanh(res, a, s);
}
int mlx_transpose(mlx_array* res, const mlx_array a, const mlx_stream s) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_transpose(res, a, s);
}
int mlx_transpose_axes(mlx_array* res, const mlx_array a, const int* axes, size_t axes_num, const mlx_stream s) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_transpose_axes(res, a, axes, axes_num, s);
}
int mlx_tril(mlx_array* res, const mlx_array x, int k, const mlx_stream s) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_tril(res, x, k, s);
}
int mlx_vector_array_free(mlx_vector_array vec) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_vector_array_free(vec);
}
int mlx_vector_array_get(mlx_array* res, const mlx_vector_array vec, size_t idx) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_vector_array_get(res, vec, idx);
}
mlx_vector_array mlx_vector_array_new(void) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return (mlx_vector_array){0}; }
  return mlx_dispatch.mlx_vector_array_new();
}
mlx_vector_array mlx_vector_array_new_data(const mlx_array* data, size_t size) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return (mlx_vector_array){0}; }
  return mlx_dispatch.mlx_vector_array_new_data(data, size);
}
mlx_vector_array mlx_vector_array_new_value(const mlx_array val) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return (mlx_vector_array){0}; }
  return mlx_dispatch.mlx_vector_array_new_value(val);
}
size_t mlx_vector_array_size(mlx_vector_array vec) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 0; }
  return mlx_dispatch.mlx_vector_array_size(vec);
}
int mlx_vector_string_free(mlx_vector_string vec) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_vector_string_free(vec);
}
mlx_vector_string mlx_vector_string_new(void) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return (mlx_vector_string){0}; }
  return mlx_dispatch.mlx_vector_string_new();
}
mlx_vector_string mlx_vector_string_new_data(const char** data, size_t size) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return (mlx_vector_string){0}; }
  return mlx_dispatch.mlx_vector_string_new_data(data, size);
}
int mlx_where(mlx_array* res, const mlx_array condition, const mlx_array x, const mlx_array y, const mlx_stream s) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_where(res, condition, x, y, s);
}
int mlx_zeros(mlx_array* res, const int* shape, size_t shape_num, mlx_dtype dtype, const mlx_stream s) {
  if (!mlx_shim_ready()) { mlx_shim_report_notloaded(); return 1; }
  return mlx_dispatch.mlx_zeros(res, shape, shape_num, dtype, s);
}